buzzer.error_melody:
  type: Integer
  note: "Melody that is played during error: </br> - 0 means anoying beep melody (500 ms enabled, 500 disabled),</br>- 1 means tolerable melody (500 ms enabled, 2500 ms disabled) </br>- 2 means bimmer melody </br>- [3, 126] - reserved, no melody </br>- 127 constant sound defined by buzzer.frequency and buzzer.duration."
  enum: PARAM_BUZZER_ERROR_MELODY
  flags: mutable
  default: 0
  min: 0
  max: 127

buzzer.arm_melody:
  type: Integer
  note: "Melody that is played when the vehicle is armed. Not implemented at the momement."
  enum: PARAM_BUZZER_ARM_MELODY
  flags: mutable
  default: 0
  min: 0
  max: 0

buzzer.frequency:
  type: Integer
  note: This parameter is applied only if buzzer.melody=127. It means PWM Frequency, Hz.
  enum: PARAM_BUZZER_FREQUENCY
  flags: mutable
  default: 5
  min: 1
  max: 100000

buzzer.duration:
  type: Integer
  note: This parameter is applied only if buzzer.melody=127. It means PWM duration, us.
  enum: PARAM_BUZZER_DURATION
  flags: mutable
  default: 0
  min: 0
  max: 100000

buzzer.verbose:
  type: Integer
  note: Indicates the operational mode of the node. When set to 1, the uavcan.equipment.indication.BeepCommand will be transmitted, including the current Buzzer frequency and duration. 
  enum: PARAM_BUZZER_VERBOSE
  flags: mutable
  default: 0
  min: 0
  max: 1
