battery.soc_pct:
  type: Integer
  note: "Percent of the full charge [-1, 127]: </br> - Value of -1 means auto estimation (doesn't work at the moment), </br> - [0, 100] means constant percent, </br> - [101, 127] means constants as well, but the values are incorrect for an autopilot."
  enum: PARAM_BATTERY_SOC_PCT
  flags: mutable
  default: -1
  min: -1
  max: 127

battery.battery_id:
  type: Integer
  note: Value of battery_id field in BatteryInfo message
  enum: PARAM_BATTERY_ID
  flags: mutable
  default: 0
  min: 0
  max: 255

battery.model_instance_id:
  type: Integer
  note: Value of model_instance_id field in BatteryInfo message
  enum: PARAM_BATTERY_MODEL_INSTANCE_ID
  flags: mutable
  default: 0
  min: 0
  max: 0

battery.capacity_mah:
  type: Integer
  note: Full battery capacity, mAh. Default is 20000 mAh. We have 4 [Tattu 10000 mAh 6S Lipo Battery](https://genstattu.com/tattu-plus-22-2v-25c-6s-liPo-battery-10000-mah-with-as150-xt150-plug.html) (2 in parallel, 2 in seies).
  enum: PARAM_BATTERY_CAPACITY_MAH
  flags: mutable
  default: 20000
  min: 4000
  max: 80000

battery.full_voltage_mv:
  type: Integer
  note: Full battery voltage, mV.
  enum: PARAM_BATTERY_FULL_VOLTAGE_MV
  flags: mutable
  default: 50400
  min: 5000
  max: 100000

battery.empty_voltage_mv:
  type: Integer
  note: Full battery voltage, mV.
  enum: PARAM_BATTERY_EMPTY_VOLTAGE_MV
  flags: mutable
  default: 39060
  min: 3000
  max: 100000

battery.current_offset_ma:
  type: Integer
  note: Current sensor measurement offset, mA. </br> I = offset_ma * 0.001 + MULTIPLIER * raw_adc
  enum: PARAM_BATTERY_CURRENT_OFFSET_MA
  flags: mutable
  default: 0
  min: -5000
  max: 0

battery.max_current:
  type: Integer
  note: Max measurement current
  enum: PARAM_BATTERY_MAX_CURRENT
  flags: mutable
  default: 200
  min: 0
  max: 1000

battery.enable_thermistor_up:
  type: Integer
  note: Enable thermistor up
  enum: PARAM_BATTERY_ENABLE_THERMISTOR_UP
  flags: mutable
  default: 0
  min: 0
  max: 1

battery.enable_thermistor_down:
  type: Integer
  note: Enable thermistor down
  enum: PARAM_BATTERY_ENABLE_THERMISTOR_DOWN
  flags: mutable
  default: 0
  min: 0
  max: 1

battery.resistance:
  type: Integer
  note: Resistor, mOhm. It is used in the current compensation algorithm.
  enum: PARAM_BATTERY_RESISTOR_MILLI_OHM
  flags: mutable
  default: 28
  min: 24
  max: 120
